# Generated by Django 5.1.7 on 2025-04-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='object_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
