# Generated by Django 5.1.6 on 2025-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='read_time',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/article_img'),
        ),
    ]
