# Generated by Django 5.1.6 on 2025-03-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_articlesmodel_read_time_alter_articlesmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='section',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='source',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/news_img'),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='category',
            field=models.CharField(choices=[('all', 'ALL'), ('student', 'student'), ('life', 'life'), ('campus life', 'Campus Life'), ('travel', 'Travel'), ('advice', 'Advice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='read_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventsmodel',
            name='attendees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('all', 'ALL'), ('environment', 'Environment'), ('campus', 'Campus'), ('sports', 'Sports'), ('academics', 'Academics'), ('research', 'Research')], max_length=50),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='read_time',
            field=models.CharField(max_length=50),
        ),
    ]
