# Generated by Django 5.1.7 on 2025-03-19 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_remove_eventsmodel_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsmodel',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='eventsmodel',
            name='isRegistered',
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='category',
            field=models.CharField(choices=[('all', 'ALL'), ('student', 'Student'), ('life', 'Life'), ('campus life', 'Campus Life'), ('travel', 'Travel'), ('advice', 'Advice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='excerpt',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='read_time',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventsmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='likes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='read_time',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
