# Generated by Django 5.1.7 on 2025-03-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_remove_eventsmodel_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
