# Generated by Django 5.1.7 on 2025-03-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_alter_eventsmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
