# Generated by Django 5.1.7 on 2025-04-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_article_bookmark_comment_event_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('environment', 'Environment'), ('campus', 'Campus'), ('sports', 'Sports'), ('academics', 'Academics'), ('research', 'Research')], default='all', max_length=50),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
