# Generated by Django 5.1.7 on 2025-04-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_remove_comment_content_type_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='public_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='public_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='public_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
