# Generated by Django 5.1.7 on 2025-04-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0009_article_public_id_event_public_id_news_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
    ]
