# Generated by Django 5.1.7 on 2025-04-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0010_remove_news_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='public_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
