# Generated by Django 5.1.7 on 2025-04-21 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0011_alter_article_public_id_alter_event_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotTopics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='uploads/HotTopics/')),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
